export const GETDATA = 'GETDATA'
export const ERROR_FROM_SERVER = 'ERROR_FROM_SERVER'
export const REQDATA = 'REQDATA'
export const REQCARTDATA = 'REQCARTDATA'
export const REQ_SINGLE_PRODUCT = 'REQ_SINGLE_PRODUCT'
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'

export const REQ_LOGIN = 'REQ_LOGIN'
export const REQ_LOGIN_SUCCESS = 'REQ_LOGIN_SUCCESS'
export const REQ_LOGIN_ERROR = 'REQ_LOGIN_ERROR'
export const REQ_LOGOUT = 'REQ_LOGOUT'
export const REQ_LOGOUT_SUCCESS = 'REQ_LOGOUT_SUCCESS'

export const REQ_REGISTER = 'REQ_REGISTER'
export const REQ_REGISTER_SUCCESS = 'REQ_REGISTER_SUCCESS'
export const REQ_REGISTER_ERROR = 'REQ_REGISTER_ERROR'

export const REQ_USERDETAILES = 'REQ_USERDETAILES'
export const REQ_USERFETCH_SUCCESS = 'REQ_USERFETCH_SUCCESS'
export const REQ_USERFETCH_ERROR = 'REQ_USERFETCH_ERROR'

export const REQ_FETCH_ALL_USER = 'REQ_FETCH_ALL_USER'
export const REQ_FETCH_ALL_USER_SUCCESS = 'REQ_FETCH_ALL_USER_SUCCESS'
export const REQ_FETCH_ALL_USER_ERROR = 'REQ_FETCH_ALL_USER_ERROR'

export const REQ_UPDATE = 'REQ_UPDATE'
export const REQ_UPDATE_SUCCESS = 'REQ_UPDATE_SUCCESS'
export const REQ_UPDATE_ERROR = 'REQ_UPDATE_ERROR'

export const REQ_DELETE = 'REQ_DELETE'
export const REQ_DELETE_SUCCESS = 'REQ_DELETE_SUCCESS'
export const REQ_DELETE_ERROR = 'REQ_DELETE_ERROR'

export const REQ_SHIPPING_ADDRESS = 'REQ_SHIPPING_ADDRESS'
export const REQ_SHIPPING_ADDRESS_REMOVE = 'REQ_SHIPPING_ADDRESS_REMOVE'
export const REQ_PAYMENT_METHOD = 'REQ_PAYMENT_METHOD'


export const REQ_ORDER = 'REQ_ORDER'
export const REQ_ORDER_SUCCESS = 'REQ_ORDER_SUCCESS'
export const REQ_ORDER_ERROR = 'REQ_ORDER_ERROR'


export const REQ_GET_ORDER = 'REQ_GET_ORDER'
export const REQ_GET_ORDER_SUCCESS = 'REQ_GET_ORDER_SUCCESS'
export const REQ_GET_ORDER_ERROR = 'REQ_GET_ORDER_ERROR'

export const REQ_GET_ALL_ORDER = 'REQ_GET_ALL_ORDER'
export const REQ_GET_ALL_ORDER_SUCCESS = 'REQ_GET_ALL_ORDER_SUCCESS'
export const REQ_GET_ALL_ORDER_ERROR = 'REQ_GET_ALL_ORDER_ERROR'

export const REQ_CHANGE_ORDER_STATUS = 'REQ_CHANGE_ORDER_STATUS'
export const REQ_CHANGE_ORDER_STATUS_SUCCESS = 'REQ_CHANGE_ORDER_STATUS_SUCCESS'
export const REQ_CHANGE_ORDER_STATUS_ERROR = 'REQ_CHANGE_ORDER_STATUS_ERROR'


export const REQ_ADMIN_INFO = 'REQ_ADMIN_INFO'
export const REQ_ADMIN_INFO_SUCCESS = 'REQ_ADMIN_INFO_SUCCESS'
export const REQ_ADMIN_INFO_ERROR = 'REQ_ADMIN_INFO_ERROR'

export const REQ_ADMIN_UPDATE_INFO = 'REQ_ADMIN_UPDATE_INFO'
export const REQ_ADMIN_UPDATE_INFO_SUCCESS = 'REQ_ADMIN_UPDATE_INFO_SUCCESS'
export const REQ_ADMIN_UPDATE_INFO_ERROR = 'REQ_ADMIN_UPDATE_INFO_ERROR'

export const REQ_ADD_NEW_MENU = 'REQ_ADD_NEW_MENU'
export const REQ_ADD_NEW_MENU_SUCCESS = 'REQ_ADD_NEW_MENU_SUCCESS'
export const REQ_ADD_NEW_MENU_ERROR = 'REQ_ADD_NEW_MENU_ERROR'

export const REQ_UPDATE_MENU = 'REQ_UPDATE_MENU'
export const REQ_UPDATE_MENU_SUCCESS = 'REQ_UPDATE_MENU_SUCCESS'
export const REQ_UPDATE_MENU_ERROR = 'REQ_UPDATE_MENU_ERROR'

export const REQ_DELETE_MENU = 'REQ_DELETE_MENU'
export const REQ_DELETE_MENU_SUCCESS = 'REQ_DELETE_MENU_SUCCESS'
export const REQ_DELETE_MENU_ERROR = 'REQ_DELETE_MENU_ERROR'

